##### Custom Deploy Tasks for cpanel ######
---
deployment:
  tasks:
    - export DEPLOY_PATH=~/media.redtrain.me/uploads/WinterBunkers
    - /bin/mkdir -p $DEPLOY_PATH
    - /bin/rm -rf $DEPLOY_PATH/data # Remove directory to clean data
    - /bin/rm -f $DEPLOY_PATH/WinterBunkers.zip # Clean old zip
    - /bin/cp pack.mcmeta $DEPLOY_PATH
    - /bin/cp -R data $DEPLOY_PATH
    - cd ~/repositories/WinterBunkers/
    - /bin/zip $DEPLOY_PATH/WinterBunkers.zip -r WinterBunkers/ -x '*.git*' -x '*.cpanel.yml'"
